[theme]
primaryColor = "#B8985C"
backgroundColor = "#FAFAF9"
secondaryBackgroundColor = "#F5F5F4"
textColor = "#1C1917"
font = "sans serif"
base = "light"

[browser]
gatherUsageStats = false

[server]
runOnSave = true
headless = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
